<a href="https://colab.research.google.com/github/SubhamDey2004-coder/deep-learning/blob/main/Backpropagation_regression_using_keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['cgpa', 'profile_score', 'lpa'])

In [ ]:
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [ ]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [ ]:
model = Sequential()

model.add(Dense(2,activation='linear',input_dim=2))
model.add(Dense(1, activation='linear'))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_1 (Dense)                 │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.get_weights()

[array([[-0.13803077,  0.13776004],
        [-0.15257895,  0.2954055 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[ 1.2629472],
        [-1.1487141]], dtype=float32),
 array([0.], dtype=float32)]

In [ ]:
new_weights = [np.array([[0.1,0.1], [0.1,0.1]], dtype = np.float32),
               np.array([0.,0.], dtype=np.float32),
               np.array([[0.1],[0.1]], dtype=np.float32),
               np.array([0.], dtype=np.float32)]

In [ ]:
model.set_weights(new_weights)

In [ ]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [ ]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error', optimizer=optimizer)

In [ ]:
model.fit(df.iloc[:,0:-1].values,df['lpa'].values,epochs=75,verbose=1,batch_size=1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 34.2436 
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 27.2058
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 32.4977
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 32.1244
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 26.1802 
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 32.3527 
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 25.4929
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 29.2082
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 19.4352 
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 24.3471 
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 23.8987 
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 23.4743
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 23.0847
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 20.9707 
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 26.1320 
Epoch 16/75

In [ ]:
model.get_weights()

[array([[0.37354115, 0.37354115],
        [0.3653723 , 0.3653723 ]], dtype=float32),
 array([0.2721392, 0.2721392], dtype=float32),
 array([[0.37273493],
        [0.37273493]], dtype=float32),
 array([0.20448865], dtype=float32)]